/* ケロちゃん ぴよぴよポン in every language: [Tiếng Việt, English, 한국어] (see js/lang.js). */
Lang.add({
  'だれが あそぶ？': ['Ai chơi nào?', 'Who is playing?', '누가 할래?'],
  'なまえなし': ['Chưa có tên', 'No name', '이름 없음'],
  'とじる': ['Đóng', 'Close', '닫기'],
  // title
  'ケロちゃん ぴよぴよポン': ['Kero Chíp Chíp Bùm', 'Kero Chick Pop', '케로 삐약삐약 퐁'],
  'おなじ いろを 3つ くっつけよう！': ['Ghép 3 quả trứng cùng màu nhé!', 'Match 3 of the same colour!', '같은 색 3개를 붙여 봐!'],
  'メニューに もどる': ['Về menu', 'Back to the menu', '메뉴로 돌아가기'],
  'ホームに ついか': ['Thêm vào màn hình', 'Add to Home', '홈 화면에 추가'],
  'こうかおん': ['Âm thanh', 'Sound effects', '효과음'],
  'おんがく': ['Nhạc', 'Music', '음악'],
  'おと': ['Âm thanh', 'Sound', '소리'],
  'はやさ': ['Tốc độ', 'Speed', '속도'],
  'ゆっくり': ['Chậm', 'Slow', '느리게'],
  'ふつう': ['Vừa', 'Normal', '보통'],
  'はやい': ['Nhanh', 'Fast', '빠르게'],
  'おに': ['Siêu khó', 'Super hard'],   // (おに, 2026-09-30; no Korean from here on)
  'あそぶ': ['Chơi', 'Play', '놀자'],
  'エンドレス': ['Chơi mãi', 'Endless', '끝없이'],
  'おみせ': ['Cửa hàng', 'Shop', '가게'],
  '管理者メニュー': ['Menu quản lý', 'Admin menu', '관리자 메뉴'],
  'もどる': ['Quay lại', 'Back', '뒤로'],
  // worlds and stages
  'ワールドを えらぼう': ['Chọn thế giới', 'Pick a world', '월드를 골라 봐'],
  'ワールド {n}': ['Thế giới {n}', 'World {n}', '월드 {n}'],
  'ステージ': ['Màn chơi', 'Stages', '스테이지'],
  'ヒント': ['Gợi ý', 'Hint', '힌트'],
  'もういちど': ['Chơi lại', 'Try again', '다시 하기'],
  'つぎへ': ['Tiếp theo', 'Next', '다음'],
  'ぴよぴよ はらっぱ': ['Cánh đồng chíp chíp', 'Chirpy Meadow', '삐약삐약 들판'],
  'ドッカン おはなばたけ': ['Vườn hoa bùm bùm', 'Boom Boom Garden', '쾅쾅 꽃밭'],
  'にじいろ おそら': ['Bầu trời cầu vồng', 'Rainbow Sky', '무지개 하늘'],
  'ピカピカ もり': ['Khu rừng lấp lánh', 'Sparkly Forest', '반짝반짝 숲'],
  'ころころ いしの くに': ['Xứ sở đá lăn', 'Rolling Stone Land', '데굴데굴 돌 나라'],
  // tips
  'ゆびで ねらって はなすと とぶよ\nおなじ いろを 3つ くっつけよう！': ['Ngắm bằng ngón tay, thả ra là trứng bay\nGhép 3 quả cùng màu nhé!', 'Aim with your finger, let go to shoot\nMatch 3 of the same colour!', '손가락으로 겨누고 떼면 날아가\n같은 색 3개를 붙여 봐!'],
  'かべに あてると はねかえるよ': ['Trứng chạm tường sẽ nảy lại', 'Eggs bounce off the walls', '벽에 맞으면 튕겨 나와'],
  'うえの たまごが われると\nぶらさがってる たまごも おちるよ': ['Trứng phía trên vỡ thì\ntrứng treo bên dưới cũng rơi', 'When the eggs above pop,\nthe hanging eggs fall too', '위의 알이 깨지면\n매달린 알도 떨어져'],
  'だっこしてる たまごを\nタッチすると いれかえられるよ': ['Chạm vào quả trứng đang ôm\nđể đổi sang quả khác', 'Tap the egg Kero is holding\nto swap it', '안고 있는 알을\n터치하면 바꿀 수 있어'],
  'たまごは だんだん おりてくるよ\nせんまで きたら たいへん！': ['Trứng sẽ dần dần đi xuống\nChạm vạch là nguy to!', 'The eggs slowly come down\nDon\'t let them reach the line!', '알이 조금씩 내려와\n선까지 오면 큰일!'],
  'ばくだんたまごは\nまわりを まとめて ドカン！': ['Trứng bom làm nổ tung\ncả những quả xung quanh — Bùm!', 'A bomb egg blasts\neverything around it — boom!', '폭탄 알은\n주변을 한꺼번에 쾅!'],
  'にじいろたまごは\nくっついた いろに へんしん！': ['Trứng cầu vồng biến thành\nmàu của quả nó chạm vào!', 'A rainbow egg turns into\nthe colour it touches!', '무지개 알은\n붙은 색으로 변신!'],
  'かみなりたまごは\nよこ いちれつを ピカッ！': ['Trứng sấm sét quét sạch\ncả một hàng ngang — Xoẹt!', 'A lightning egg zaps\na whole row — flash!', '번개 알은\n가로 한 줄을 번쩍!'],
  'いしの たまごは われないよ\nうえを けして おとそう！': ['Trứng đá không vỡ đâu\nPhá trứng phía trên để nó rơi nhé!', 'Stone eggs don\'t pop\nClear above them to drop them!', '돌 알은 깨지지 않아\n위를 없애서 떨어뜨려!'],
  // while playing and at the end
  'すごすぎ！': ['Siêu quá!', 'Amazing!', '최고야!'],
  'すごい！': ['Giỏi quá!', 'Great!', '대단해!'],
  'いいね！': ['Tốt lắm!', 'Nice!', '좋아!'],
  'さいこう {n}': ['Kỷ lục {n}', 'Best {n}', '최고 {n}'],
  'かんぺき！': ['Hoàn hảo!', 'Perfect!', '완벽해!'],
  'おに クリア！': ['Qua mức Siêu khó!', 'Super hard clear!'],
  'やったね！': ['Làm được rồi!', 'You did it!', '해냈다!'],
  'ぜんぶ クリア！': ['Qua hết rồi!', 'All clear!', '모두 클리어!'],
  'ワールド クリア！': ['Xong thế giới!', 'World clear!', '월드 클리어!'],
  'ひよこが <b>{n}</b>わ うまれたよ！': ['Đã nở <b>{n}</b> chú gà con!', '<b>{n}</b> chicks hatched!', '병아리가 <b>{n}</b>마리 태어났어!'],
  'ひよこが <b>{n}</b>わ うまれたよ！<br>さいこう {best}わ': ['Đã nở <b>{n}</b> chú gà con!<br>Kỷ lục: {best}', '<b>{n}</b> chicks hatched!<br>Best: {best}', '병아리가 <b>{n}</b>마리 태어났어!<br>최고 {best}마리'],
  'ざんねん…': ['Tiếc quá…', 'Oh no…', '아쉬워…'],
  'たまごが せんまで きちゃった': ['Trứng chạm tới vạch mất rồi', 'The eggs reached the line', '알이 선까지 내려왔어'],
  'しんきろく！': ['Kỷ lục mới!', 'New record!', '신기록!'],
  'おしまい！': ['Kết thúc!', 'The end!', '끝!'],
  // shop
  'ケロちゃん': ['Kero', 'Kero', '케로'],
  'ミミちゃん': ['Mimi', 'Mimi', '미미'],
  'ニャーちゃん': ['Meo Meo', 'Meow', '야옹이'],
  'ワンちゃん': ['Gâu Gâu', 'Woof', '멍멍이'],
  '★を つかって おともだちを ふやそう！': ['Dùng ★ để có thêm bạn mới nhé!', 'Use your ★ to make new friends!', '★로 새 친구를 만들자!'],
  'つかってる': ['Đang chọn', 'Chosen', '함께하는 중'],
  'えらぶ': ['Chọn', 'Choose', '고르기'],
  '{star}{price} で かう': ['Mua {star}{price}', 'Buy {star}{price}', '{star}{price}에 사기'],
  'あと ★{n} で かえるよ': ['Cần thêm ★{n} nữa là mua được', '{n} more ★ to buy it', '★{n}개만 더 모으면 살 수 있어'],
  '{name}を<br>{star}{price} で かう？': ['Mua {name}<br>với {star}{price} nhé?', 'Buy {name}<br>for {star}{price}?', '{name}를<br>{star}{price}에 살까?'],
  '{name}が なかまに なったよ！': ['{name} đã thành bạn rồi!', '{name} is your friend now!', '{name}가 친구가 되었어!'],
  'やめる': ['Thôi', 'Cancel', '취소'],
  'かう': ['Mua', 'Buy', '살래'],
  // admin (for grown-ups)
  '管理者パスワード': ['Mật khẩu quản lý', 'Admin password', '관리자 비밀번호'],
  'けす': ['Xóa', 'Del', '지우기'],
  '閉じる': ['Đóng', 'Close', '닫기'],
  '全ステージ解放：オン': ['Mở khóa mọi màn: Bật', 'Unlock all stages: On', '모든 스테이지 열기: 켬'],
  '全ステージ解放：オフ': ['Mở khóa mọi màn: Tắt', 'Unlock all stages: Off', '모든 스테이지 열기: 끔'],
  '記録をリセット': ['Xóa kỷ lục', 'Reset records', '기록 초기화'],
  'もう一度押すと消えます': ['Nhấn lần nữa để xóa', 'Press again to erase', '한 번 더 누르면 지워져요'],
  'あつめた★ {got}　つかった★ {spent}': ['★ đã nhặt: {got}　★ đã dùng: {spent}', '★ collected: {got}　★ spent: {spent}', '모은 ★ {got}　쓴 ★ {spent}']
});

// The big title, one line per row (each letter hops on its own).
var GAME_LOGO = { ja: ['ケロちゃん', 'ぴよぴよポン'], vi: ['Kero', 'Chíp Chíp Bùm'], en: ['Kero', 'Chick Pop'], ko: ['케로', '삐약삐약 퐁'] };
